//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartiys_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calisan
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Cinsiyet { get; set; }
        public Nullable<bool> Askerlik { get; set; }
        public string Mezuniyet { get; set; }
        public Nullable<long> TC { get; set; }
        public Nullable<long> Telefon { get; set; }
        public string Adres { get; set; }
        public string AyrilmaNedeni { get; set; }
        public string KanGrubu { get; set; }
        public Nullable<int> DepartmanID { get; set; }
        public Nullable<int> CalismaSuresiID { get; set; }
        public Nullable<int> GorevID { get; set; }
        public Nullable<int> UretimSafhaID { get; set; }
        public Nullable<int> SiparisID { get; set; }
        public Nullable<int> BantID { get; set; }
    }
}
