//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartiys_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Makina
    {
        public int ID { get; set; }
        public string Kod { get; set; }
        public string SeriNo { get; set; }
        public string Ad { get; set; }
        public string Marka { get; set; }
        public string Cins { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string Ozellik { get; set; }
        public string Grup { get; set; }
    }
}
