//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartiys_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartDataBase : DbContext
    {
        public SmartDataBase()
            : base("name=SmartDataBase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BantTanim> BantTanim { get; set; }
        public DbSet<Beden> Beden { get; set; }
        public DbSet<Calisan> Calisan { get; set; }
        public DbSet<CalismaSureleri> CalismaSureleri { get; set; }
        public DbSet<CalismaTarihi> CalismaTarihi { get; set; }
        public DbSet<Departman> Departman { get; set; }
        public DbSet<Durum> Durum { get; set; }
        public DbSet<Gorev> Gorev { get; set; }
        public DbSet<Grup> Grup { get; set; }
        public DbSet<Islemler> Islemler { get; set; }
        public DbSet<Makina> Makina { get; set; }
        public DbSet<Model> Model { get; set; }
        public DbSet<ParaBirimi> ParaBirimi { get; set; }
        public DbSet<ParaDonusum> ParaDonusum { get; set; }
        public DbSet<Renk> Renk { get; set; }
        public DbSet<Siparis> Siparis { get; set; }
        public DbSet<Terminal> Terminal { get; set; }
        public DbSet<Uretim> Uretim { get; set; }
        public DbSet<UretimSafha> UretimSafha { get; set; }
    }
}
