//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartiys_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public Nullable<System.DateTime> VerilisTarihi { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<int> BedenID { get; set; }
        public Nullable<int> ParaBirimiID { get; set; }
        public Nullable<int> DepartmanID { get; set; }
        public string TeslimAdresi { get; set; }
        public string TeslimFirma { get; set; }
        public Nullable<int> BantID { get; set; }
    }
}
